name: radarsofttask
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get: ^4.6.6
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  url_launcher: ^6.2.1
  google_maps_flutter: ^2.5.0
  shimmer: ^3.0.0
  rxdart: ^0.27.7
  bloc: ^8.1.2
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:


  uses-material-design: true

  assets:
    - assets/images/

